Link table
touredri/sql pull request #5
Opened 2023-06-09 18:56 UTC by touredri

In this PR we used join to link table and show based on different criteria 

![Capture d’écran 2023-06-09 093336](https://github.com/touredri/sql/assets/112565844/33c6b565-6c55-44e9-b3c8-12d7d929717d)
![Capture d’écran 2023-06-09 093416](https://github.com/touredri/sql/assets/112565844/6b01734f-2466-48b2-a281-462ac2c6500c)
![Capture d’écran 2023-06-09 093750](https://github.com/touredri/sql/assets/112565844/9cd5217f-db0d-48c3-8f44-78d986d21b97)
![Capture d’écran 2023-06-09 093840](https://github.com/touredri/sql/assets/112565844/aaf2f9e2-ecda-40fc-9bdc-6ada6c66b8cb)
![Capture d’écran 2023-06-09 093917](https://github.com/touredri/sql/assets/112565844/0f083c77-4170-410d-b523-8b4de7c10c75)
![Capture d’écran 2023-06-09 094655](https://github.com/touredri/sql/assets/112565844/376421a6-2810-4cbc-af8c-b63aff55d2e6)
![Capture d’écran 2023-06-09 094802](https://github.com/touredri/sql/assets/112565844/4b394f2a-5f9c-4953-a3f4-944ab19cb248)
![Capture d’écran 2023-06-09 191831](https://github.com/touredri/sql/assets/112565844/9b2f4a8d-fa45-4a04-8314-b7c3ca74ec11)
![Capture d’écran 2023-06-09 193312](https://github.com/touredri/sql/assets/112565844/ab00e4d6-1170-48fa-8482-0fdf33dcad0e)

2023-06-09 19:01 UTC, Kamba56 commented
Hi @touredri

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly remove all comments that are there to guide you to fill in the readme template.
![image](https://github.com/touredri/sql/assets/94551484/556b3ac6-4972-447a-a87b-c1fb256beea8)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-09 21:17 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @touredri 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️ visits and specializations tables are created
✔️ The required data is inserted for visits and specialization tables
## Required Changes ♻️
_Check the comments under the review._

- [ ] Please remove all the comments from your readme.md file.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 21:17 UTC, tugsem commented on schema.sql
- [ ] Kindly add the table for "vets" as per the requirement: 
![image](https://github.com/touredri/sql/assets/91486791/2e7270ba-91de-45cc-9692-18998fd58680)

2023-06-09 21:17 UTC, tugsem commented on data.sql
> +
- [ ] Kindly add these data to your newly created "vets" table as per the requirement:
![image](https://github.com/touredri/sql/assets/91486791/5e077dd9-ac8d-48ea-a3d5-ac8293978cb3)

2023-06-10 05:39 UTC, touredri commented on data.sql
> +
I forgot @tugsem

2023-06-10 05:54 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi @touredri 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Understand the different types of relationships between tables.
- ✔️ Prepare complex queries that answer analytical questions.
- ✔️ Use primary key & foreign key mechanisms for joining tables.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 17:31 UTC, merged